import = [
    "~/.config/alacritty/themes/themes/ubuntu.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = 'MesloLGS Nerd Font Mono'
style = 'Regular'

[window]
opacity = 0.8
padding.x = 10
padding.y = 10

